
import { SiMysql, SiArduino, SiAngular, SiLess, SiTypescript, SiLabview, SiSiemens } from "react-icons/si"
import { FaHome, FaChartBar, FaChartPie, FaUserAlt, FaReact, FaCss3, FaHtml5, FaPython, FaGithubSquare, FaJs, FaBootstrap, FaSass } from "react-icons/fa"
export const languajesFooter = {
    Spanish:'Pagina Creado Por David Antonio Toro Medina',
    English:'Page Created by David Antonio Toro Medina',
}
export const languajesMain = [
    {
        titles:{
            Spanish:'INICIO',
            English:'HOME',
        },
        icon:<FaHome/>,
        link:'/perfilReactJS'
    },
    {
        titles:{
            Spanish:'ACERCA DE MI',
            English:'ABOUT ME',
        },
        icon:<FaUserAlt/>,
        link:'/perfilReactJS/AboutMe'
    },
    {
        titles:{
            Spanish:'EXPERIENCIA',
            English:'EXPERIENCE',
        },
        icon:<FaChartBar/>,
        link:'/perfilReactJS/Experience'
    },
    {
        titles:{
            Spanish:'HABILIDADES',
            English:'SKILLS',
        },
        icon:<FaChartPie/>,
        link:'/perfilReactJS/Skill'
    },
]
export const SOFTWARE = [
    {
        software:'Visual Studio Code',
        icons:'VSC',
        color:'',
        year: 2018,
        month: 7,
        day: 1,
    },
    {
        software:'SolidWorks',
        icons:'VSC',
        color:'',
        year: 2013,
        month: 1,
        day: 1,
    },
    {
        software:'EAGLE AUTODESK',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'PROTEUS',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'ARDUINO',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'ANYDESK',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'PICPICK',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'Ultimaker Cura',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'FIGMA',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'MICROSOFT EXCEL',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'VBA',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'MICROSOFT VISIO',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'MICROSOFT POWERPOINT',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'MICROSOFT WORD',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'PROTEUS',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'XAMPP',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'LabView',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'QT DESIGNER',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'Matlab',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'CANDLE',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'LaserEngrave',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'F-ENGRAVE',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'SoMachineBasic',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'CADE SIMU',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'NEXTION',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'PSIM',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'GWORKS MITSUBISHI',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'MOVAVI EDITOR',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    },
    {
        software:'TIA PORTAL',
        icons:'VSC',
        color:'',
        year: 2017,
        month: 3,
        day: 1,
    }
]

export const SystemOP = [
    {
        system:'Windows',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Avanzado',
            English:'Advanced',
        },
        year: 1996,
        month: 7,
        day: 1,
    },
    {
        system:'Ubidots',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    }
]

export const ProgrammingLanguages = [
    {
        language:'PYTHON',
        icons:<FaPython/>,
        color:'#00b33c',
        level:{
            Spanish:'Avanzado',
            English:'Advanced',
        },
        library:[
            {
                library: 'FLASK',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'DJANGO',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'MYSQL - CONECTOR',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'PANDAS',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'PYQT5',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'PAHO - MQTT',
                year: 1996,
                month: 7,
                day: 1,
            },
            {
                library: 'JSON',
                year: 1996,
                month: 7,
                day: 1,
            }
        ],
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'REACT',
        icons:<FaReact/>,
        color:'#00A1F1',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2018,
        month: 7,
        day: 1,
    },
    {
        language:'ANGULAR',
        icons:<SiAngular/>,
        color:'#ff0000',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2019,
        month: 7,
        day: 1,
    },
    {
        language:'ARDUINO',
        icons:<SiArduino/>,
        color:'#009973',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2013,
        month: 7,
        day: 1,
    },
    {
        language:'C ++',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2015,
        month: 7,
        day: 1,
    },
    {
        language:'JAVASCRIPT',
        icons:<FaJs/>,
        color:'#ffcc00',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'TYPESCRIPT',
        icons:<SiTypescript/>,
        color:'#000080',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'SIEMENS PLC',
        icons:<SiSiemens/>,
        color:'#34A853',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        library:[
            {
                library: 'TIA PORTAL',
                year: 1996,
                month: 7,
                day: 1,
            }
        ],
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'ROS',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'LABVIEW',
        icons:<SiLabview/>,
        color:'Orange',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'MATLAB',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'CSS3',
        icons:<FaCss3/>,
        color:'#3B5998',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'HTML5',
        icons:<FaHtml5/>,
        color:'#F65314',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'GIT / GITHUB',
        icons:<FaGithubSquare/>,
        color:'black',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'BOOSTRAP',
        icons:<FaBootstrap/>,
        color:'#8000ff',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'SASS',
        icons:<FaSass/>,
        color:'#ff4db8',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'LESS',
        icons:<SiLess/>,
        color:'#000099',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    },
    {
        language:'MYSQL / SQL',
        icons:<SiMysql/>,
        color:'#3333ff',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    }
    ,
    {
        language:'MONGODB',
        icons:'VSC',
        color:'',
        level:{
            Spanish:'Intermedio',
            English:'Intermediate',
        },
        year: 2016,
        month: 7,
        day: 1,
    }
]